### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by silverbullettruck2001** [lib-ruby-parser/node-bindings#4]
I am trying to start using this, but the example in the project doesn't seem to work.  Does the example you provide in the `README.md` need to be updated or am I doing something wrong?  When I try to use the example it throws the following error:
```Uncaught TypeError TypeError: `input` argument must be a String```

I tried changing the input to a string, and then it throws the error:
```Uncaught TypeError TypeError: `buffer_name` argument must be a String```

Here is what I have for my code:
```import rubyparse from 'lib-ruby-parser';
const { parse, Send } = rubyparse;

function print_parse_result(parser_result) {
  console.log(inspect(parser_result, { showHidden: false, depth: null }));
}

// This function must be defined by you.
// It takes a string and return an array of bytes.
// The following code is just an example:
function bytes(str) {
  const bytes = unescape(encodeURIComponent(str))
    .split('')
    .map((c) => c.charCodeAt(0));
  return new Uint8Array(bytes);
}

const input = bytes('2 + 3 # x');
const options = { record_tokens: true };
const result = parse(input, options);
print_parser_result(result);
```

Could you provide some guidence on what is expected to make the example work correctly?

Thanks!

**Comment by iliabylich** [comment]
Hmm, yes, I think this particular bindings can have an outdated documentation. Are you using the latest version? (`4.0.3`) If so for now you can take a look at specs - https://github.com/lib-ruby-parser/node-bindings/blob/master/spec/bindings.spec.ts#L21, I've simplified the signature to be `parse("source code", "buffer name", decoder_fn)`. Could you try that for now and let me know if works?

I'll fix the documentation, thanks for reporting!

**Comment by silverbullettruck2001** [comment]
@iliabylich Thanks, that's what I needed to keep moving.  Thanks for your work on this!
